// @generated drizzle-zero signature:sha256:3faa6cb79c46016aec2dc80ac6788edd92ee18930343a9bc3a56b77bd12e3d24
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const demoItemsTable = {
  name: "demo_items",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    _tag: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    created_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    created_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    updated_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updated_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    deleted_at: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    deleted_by: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    owner_user_id: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    demo_items: demoItemsTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "demo_items" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DemoItem = Row<(typeof schema)["tables"]["demo_items"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
