name: church-work

services:
  church_work_postgres:
    image: postgres:16-alpine
    network_mode: bridge
    shm_size: 1g
    user: postgres
    restart: always
    healthcheck:
      test: "pg_isready -U postgres --dbname=church_work"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: church_work
      POSTGRES_PASSWORD: postgres
    command: |
      postgres
      -c wal_level=logical
      -c max_wal_senders=10
      -c max_replication_slots=5
      -c hot_standby=on
      -c hot_standby_feedback=on
      -c max_connections=200
    volumes:
      - church_work_pgdata:/var/lib/postgresql/data

volumes:
  church_work_pgdata:
    driver: local
